package com.apap.director.director_db.dao.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.apap.director.director_db.dao.model.Contact;
import com.apap.director.director_db.dao.model.Conversation;
import com.apap.director.director_db.dao.model.Message;
import com.apap.director.director_db.dao.model.IdentityKey;
import com.apap.director.director_db.dao.model.PreKey;
import com.apap.director.director_db.dao.model.Session;
import com.apap.director.director_db.dao.model.SignedPreKey;

import com.apap.director.director_db.dao.model.ContactDao;
import com.apap.director.director_db.dao.model.ConversationDao;
import com.apap.director.director_db.dao.model.MessageDao;
import com.apap.director.director_db.dao.model.IdentityKeyDao;
import com.apap.director.director_db.dao.model.PreKeyDao;
import com.apap.director.director_db.dao.model.SessionDao;
import com.apap.director.director_db.dao.model.SignedPreKeyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig conversationDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig identityKeyDaoConfig;
    private final DaoConfig preKeyDaoConfig;
    private final DaoConfig sessionDaoConfig;
    private final DaoConfig signedPreKeyDaoConfig;

    private final ContactDao contactDao;
    private final ConversationDao conversationDao;
    private final MessageDao messageDao;
    private final IdentityKeyDao identityKeyDao;
    private final PreKeyDao preKeyDao;
    private final SessionDao sessionDao;
    private final SignedPreKeyDao signedPreKeyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        identityKeyDaoConfig = daoConfigMap.get(IdentityKeyDao.class).clone();
        identityKeyDaoConfig.initIdentityScope(type);

        preKeyDaoConfig = daoConfigMap.get(PreKeyDao.class).clone();
        preKeyDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        signedPreKeyDaoConfig = daoConfigMap.get(SignedPreKeyDao.class).clone();
        signedPreKeyDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        identityKeyDao = new IdentityKeyDao(identityKeyDaoConfig, this);
        preKeyDao = new PreKeyDao(preKeyDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);
        signedPreKeyDao = new SignedPreKeyDao(signedPreKeyDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(Conversation.class, conversationDao);
        registerDao(Message.class, messageDao);
        registerDao(IdentityKey.class, identityKeyDao);
        registerDao(PreKey.class, preKeyDao);
        registerDao(Session.class, sessionDao);
        registerDao(SignedPreKey.class, signedPreKeyDao);
    }
    
    public void clear() {
        contactDaoConfig.clearIdentityScope();
        conversationDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        identityKeyDaoConfig.clearIdentityScope();
        preKeyDaoConfig.clearIdentityScope();
        sessionDaoConfig.clearIdentityScope();
        signedPreKeyDaoConfig.clearIdentityScope();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public IdentityKeyDao getIdentityKeyDao() {
        return identityKeyDao;
    }

    public PreKeyDao getPreKeyDao() {
        return preKeyDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public SignedPreKeyDao getSignedPreKeyDao() {
        return signedPreKeyDao;
    }

}
