package com.apap.director.director_db.dao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRE_KEY".
*/
public class PreKeyDao extends AbstractDao<PreKey, Long> {

    public static final String TABLENAME = "PRE_KEY";

    /**
     * Properties of entity PreKey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PreKeyId = new Property(1, Integer.class, "preKeyId", false, "PRE_KEY_ID");
        public final static Property Serialized = new Property(2, byte[].class, "serialized", false, "SERIALIZED");
    }


    public PreKeyDao(DaoConfig config) {
        super(config);
    }
    
    public PreKeyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRE_KEY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PRE_KEY_ID\" INTEGER," + // 1: preKeyId
                "\"SERIALIZED\" BLOB);"); // 2: serialized
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRE_KEY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer preKeyId = entity.getPreKeyId();
        if (preKeyId != null) {
            stmt.bindLong(2, preKeyId);
        }
 
        byte[] serialized = entity.getSerialized();
        if (serialized != null) {
            stmt.bindBlob(3, serialized);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer preKeyId = entity.getPreKeyId();
        if (preKeyId != null) {
            stmt.bindLong(2, preKeyId);
        }
 
        byte[] serialized = entity.getSerialized();
        if (serialized != null) {
            stmt.bindBlob(3, serialized);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PreKey readEntity(Cursor cursor, int offset) {
        PreKey entity = new PreKey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // preKeyId
            cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2) // serialized
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PreKey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPreKeyId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSerialized(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PreKey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PreKey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PreKey entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
