package com.apap.director.director_db.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SIGNED_PRE_KEY".
 */
@Entity
public class SignedPreKey {

    @Id(autoincrement = true)
    private Long id;
    private Integer signedPreKeyId;
    private byte[] serialized;

    @Generated
    public SignedPreKey() {
    }

    public SignedPreKey(Long id) {
        this.id = id;
    }

    @Generated
    public SignedPreKey(Long id, Integer signedPreKeyId, byte[] serialized) {
        this.id = id;
        this.signedPreKeyId = signedPreKeyId;
        this.serialized = serialized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSignedPreKeyId() {
        return signedPreKeyId;
    }

    public void setSignedPreKeyId(Integer signedPreKeyId) {
        this.signedPreKeyId = signedPreKeyId;
    }

    public byte[] getSerialized() {
        return serialized;
    }

    public void setSerialized(byte[] serialized) {
        this.serialized = serialized;
    }

}
