package com.apap.director.im.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "IDENTITY_KEY".
 */
@Entity
public class IdentityKey {

    @Id(autoincrement = true)
    private Long id;
    private Integer identityKeyId;
    private String name;
    private byte[] serialized;

    @Generated
    public IdentityKey() {
    }

    public IdentityKey(Long id) {
        this.id = id;
    }

    @Generated
    public IdentityKey(Long id, Integer identityKeyId, String name, byte[] serialized) {
        this.id = id;
        this.identityKeyId = identityKeyId;
        this.name = name;
        this.serialized = serialized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdentityKeyId() {
        return identityKeyId;
    }

    public void setIdentityKeyId(Integer identityKeyId) {
        this.identityKeyId = identityKeyId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getSerialized() {
        return serialized;
    }

    public void setSerialized(byte[] serialized) {
        this.serialized = serialized;
    }

}
