package com.apap.director.im.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MESSAGE".
 */
@Entity
public class Message {

    @Id(autoincrement = true)
    private Long id;
    private String sender;

    @NotNull
    private String recipient;

    @NotNull
    private String content;

    @NotNull
    private java.util.Date date;
    private long conversationId;

    @Generated
    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    @Generated
    public Message(Long id, String sender, String recipient, String content, java.util.Date date, long conversationId) {
        this.id = id;
        this.sender = sender;
        this.recipient = recipient;
        this.content = content;
        this.date = date;
        this.conversationId = conversationId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    @NotNull
    public String getRecipient() {
        return recipient;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecipient(@NotNull String recipient) {
        this.recipient = recipient;
    }

    @NotNull
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(@NotNull String content) {
        this.content = content;
    }

    @NotNull
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(@NotNull java.util.Date date) {
        this.date = date;
    }

    public long getConversationId() {
        return conversationId;
    }

    public void setConversationId(long conversationId) {
        this.conversationId = conversationId;
    }

    @Override
    public String toString() {
        return content;
    }
}
