package com.apap.director.im.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PRE_KEY".
 */
@Entity
public class PreKey {

    @Id(autoincrement = true)
    private Long id;
    private Integer preKeyId;
    private byte[] serialized;

    @Generated
    public PreKey() {
    }

    public PreKey(Long id) {
        this.id = id;
    }

    @Generated
    public PreKey(Long id, Integer preKeyId, byte[] serialized) {
        this.id = id;
        this.preKeyId = preKeyId;
        this.serialized = serialized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPreKeyId() {
        return preKeyId;
    }

    public void setPreKeyId(Integer preKeyId) {
        this.preKeyId = preKeyId;
    }

    public byte[] getSerialized() {
        return serialized;
    }

    public void setSerialized(byte[] serialized) {
        this.serialized = serialized;
    }

}
