package com.apap.director.im.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SESSION".
 */
@Entity
public class Session {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private byte[] serialized;

    @Generated
    public Session() {
    }

    public Session(Long id) {
        this.id = id;
    }

    @Generated
    public Session(Long id, String name, byte[] serialized) {
        this.id = id;
        this.name = name;
        this.serialized = serialized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getSerialized() {
        return serialized;
    }

    public void setSerialized(byte[] serialized) {
        this.serialized = serialized;
    }

}
