package com.apap.director.client.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONTACT".
 */
@Entity
public class Contact {

    @Id
    private String name;

    @Generated(hash = 672515148)
    public Contact() {
    }

    @Generated(hash = 45249444)
    public Contact(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return name;
    }

}
