package com.apap.director.db.dao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACCOUNT".
*/
public class AccountDao extends AbstractDao<Account, Long> {

    public static final String TABLENAME = "ACCOUNT";

    /**
     * Properties of entity Account.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RegistrationId = new Property(1, Long.class, "registrationId", false, "REGISTRATION_ID");
        public final static Property IdentityName = new Property(2, String.class, "identityName", false, "IDENTITY_NAME");
        public final static Property IdentityKeyPair = new Property(3, String.class, "identityKeyPair", false, "IDENTITY_KEY_PAIR");
    }


    public AccountDao(DaoConfig config) {
        super(config);
    }
    
    public AccountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACCOUNT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"REGISTRATION_ID\" INTEGER," + // 1: registrationId
                "\"IDENTITY_NAME\" TEXT," + // 2: identityName
                "\"IDENTITY_KEY_PAIR\" TEXT);"); // 3: identityKeyPair
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACCOUNT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Account entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long registrationId = entity.getRegistrationId();
        if (registrationId != null) {
            stmt.bindLong(2, registrationId);
        }
 
        String identityName = entity.getIdentityName();
        if (identityName != null) {
            stmt.bindString(3, identityName);
        }
 
        String identityKeyPair = entity.getIdentityKeyPair();
        if (identityKeyPair != null) {
            stmt.bindString(4, identityKeyPair);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Account entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long registrationId = entity.getRegistrationId();
        if (registrationId != null) {
            stmt.bindLong(2, registrationId);
        }
 
        String identityName = entity.getIdentityName();
        if (identityName != null) {
            stmt.bindString(3, identityName);
        }
 
        String identityKeyPair = entity.getIdentityKeyPair();
        if (identityKeyPair != null) {
            stmt.bindString(4, identityKeyPair);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Account readEntity(Cursor cursor, int offset) {
        Account entity = new Account( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // registrationId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // identityName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // identityKeyPair
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Account entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRegistrationId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIdentityName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdentityKeyPair(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Account entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Account entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Account entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
