package com.apap.director.db.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ACCOUNT".
 */
@Entity
public class Account {

    @Id(autoincrement = true)
    private Long id;
    private Long registrationId;
    private String identityName;
    private String identityKeyPair;

    @Generated
    public Account() {
    }

    public Account(Long id) {
        this.id = id;
    }

    @Generated
    public Account(Long id, Long registrationId, String identityName, String identityKeyPair) {
        this.id = id;
        this.registrationId = registrationId;
        this.identityName = identityName;
        this.identityKeyPair = identityKeyPair;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRegistrationId() {
        return registrationId;
    }

    public void setRegistrationId(Long registrationId) {
        this.registrationId = registrationId;
    }

    public String getIdentityName() {
        return identityName;
    }

    public void setIdentityName(String identityName) {
        this.identityName = identityName;
    }

    public String getIdentityKeyPair() {
        return identityKeyPair;
    }

    public void setIdentityKeyPair(String identityKeyPair) {
        this.identityKeyPair = identityKeyPair;
    }

}
