package com.apap.director.db.dao.model;

import org.greenrobot.greendao.annotation.*;

import com.apap.director.db.dao.model.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONTACT".
 */
@Entity(active = true)
public class Contact {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;
    private String image;
    private Long conversationId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ContactDao myDao;

    @ToOne(joinProperty = "conversationId")
    private Conversation conversation;

    @Generated
    private transient Long conversation__resolvedKey;

    @Generated
    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    @Generated
    public Contact(Long id, String name, String image, Long conversationId) {
        this.id = id;
        this.name = name;
        this.image = image;
        this.conversationId = conversationId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getContactDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Long getConversationId() {
        return conversationId;
    }

    public void setConversationId(Long conversationId) {
        this.conversationId = conversationId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Conversation getConversation() {
        Long __key = this.conversationId;
        if (conversation__resolvedKey == null || !conversation__resolvedKey.equals(__key)) {
            __throwIfDetached();
            ConversationDao targetDao = daoSession.getConversationDao();
            Conversation conversationNew = targetDao.load(__key);
            synchronized (this) {
                conversation = conversationNew;
            	conversation__resolvedKey = __key;
            }
        }
        return conversation;
    }

    @Generated
    public void setConversation(Conversation conversation) {
        synchronized (this) {
            this.conversation = conversation;
            conversationId = conversation == null ? null : conversation.getId();
            conversation__resolvedKey = conversationId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    @Override
    public String toString() {
        return name;
    }
}
