package com.apap.director.db.dao.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.apap.director.db.dao.model.Contact;
import com.apap.director.db.dao.model.Conversation;
import com.apap.director.db.dao.model.Message;
import com.apap.director.db.dao.model.DbIdentityKey;
import com.apap.director.db.dao.model.DbPreKey;
import com.apap.director.db.dao.model.DbSession;
import com.apap.director.db.dao.model.DbSignedPreKey;
import com.apap.director.db.dao.model.Account;

import com.apap.director.db.dao.model.ContactDao;
import com.apap.director.db.dao.model.ConversationDao;
import com.apap.director.db.dao.model.MessageDao;
import com.apap.director.db.dao.model.DbIdentityKeyDao;
import com.apap.director.db.dao.model.DbPreKeyDao;
import com.apap.director.db.dao.model.DbSessionDao;
import com.apap.director.db.dao.model.DbSignedPreKeyDao;
import com.apap.director.db.dao.model.AccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig conversationDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig dbIdentityKeyDaoConfig;
    private final DaoConfig dbPreKeyDaoConfig;
    private final DaoConfig dbSessionDaoConfig;
    private final DaoConfig dbSignedPreKeyDaoConfig;
    private final DaoConfig accountDaoConfig;

    private final ContactDao contactDao;
    private final ConversationDao conversationDao;
    private final MessageDao messageDao;
    private final DbIdentityKeyDao dbIdentityKeyDao;
    private final DbPreKeyDao dbPreKeyDao;
    private final DbSessionDao dbSessionDao;
    private final DbSignedPreKeyDao dbSignedPreKeyDao;
    private final AccountDao accountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        dbIdentityKeyDaoConfig = daoConfigMap.get(DbIdentityKeyDao.class).clone();
        dbIdentityKeyDaoConfig.initIdentityScope(type);

        dbPreKeyDaoConfig = daoConfigMap.get(DbPreKeyDao.class).clone();
        dbPreKeyDaoConfig.initIdentityScope(type);

        dbSessionDaoConfig = daoConfigMap.get(DbSessionDao.class).clone();
        dbSessionDaoConfig.initIdentityScope(type);

        dbSignedPreKeyDaoConfig = daoConfigMap.get(DbSignedPreKeyDao.class).clone();
        dbSignedPreKeyDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        dbIdentityKeyDao = new DbIdentityKeyDao(dbIdentityKeyDaoConfig, this);
        dbPreKeyDao = new DbPreKeyDao(dbPreKeyDaoConfig, this);
        dbSessionDao = new DbSessionDao(dbSessionDaoConfig, this);
        dbSignedPreKeyDao = new DbSignedPreKeyDao(dbSignedPreKeyDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(Conversation.class, conversationDao);
        registerDao(Message.class, messageDao);
        registerDao(DbIdentityKey.class, dbIdentityKeyDao);
        registerDao(DbPreKey.class, dbPreKeyDao);
        registerDao(DbSession.class, dbSessionDao);
        registerDao(DbSignedPreKey.class, dbSignedPreKeyDao);
        registerDao(Account.class, accountDao);
    }
    
    public void clear() {
        contactDaoConfig.clearIdentityScope();
        conversationDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        dbIdentityKeyDaoConfig.clearIdentityScope();
        dbPreKeyDaoConfig.clearIdentityScope();
        dbSessionDaoConfig.clearIdentityScope();
        dbSignedPreKeyDaoConfig.clearIdentityScope();
        accountDaoConfig.clearIdentityScope();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public DbIdentityKeyDao getDbIdentityKeyDao() {
        return dbIdentityKeyDao;
    }

    public DbPreKeyDao getDbPreKeyDao() {
        return dbPreKeyDao;
    }

    public DbSessionDao getDbSessionDao() {
        return dbSessionDao;
    }

    public DbSignedPreKeyDao getDbSignedPreKeyDao() {
        return dbSignedPreKeyDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

}
