package com.apap.director.db.dao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_IDENTITY_KEY".
*/
public class DbIdentityKeyDao extends AbstractDao<DbIdentityKey, Long> {

    public static final String TABLENAME = "DB_IDENTITY_KEY";

    /**
     * Properties of entity DbIdentityKey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeviceId = new Property(1, Integer.class, "deviceId", false, "DEVICE_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Key = new Property(3, byte[].class, "key", false, "KEY");
        public final static Property IdentityName = new Property(4, String.class, "identityName", false, "IDENTITY_NAME");
    }


    public DbIdentityKeyDao(DaoConfig config) {
        super(config);
    }
    
    public DbIdentityKeyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_IDENTITY_KEY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DEVICE_ID\" INTEGER," + // 1: deviceId
                "\"NAME\" TEXT," + // 2: name
                "\"KEY\" BLOB," + // 3: key
                "\"IDENTITY_NAME\" TEXT);"); // 4: identityName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_IDENTITY_KEY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbIdentityKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(2, deviceId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        byte[] key = entity.getKey();
        if (key != null) {
            stmt.bindBlob(4, key);
        }
 
        String identityName = entity.getIdentityName();
        if (identityName != null) {
            stmt.bindString(5, identityName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbIdentityKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindLong(2, deviceId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        byte[] key = entity.getKey();
        if (key != null) {
            stmt.bindBlob(4, key);
        }
 
        String identityName = entity.getIdentityName();
        if (identityName != null) {
            stmt.bindString(5, identityName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbIdentityKey readEntity(Cursor cursor, int offset) {
        DbIdentityKey entity = new DbIdentityKey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // deviceId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3), // key
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // identityName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbIdentityKey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setKey(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
        entity.setIdentityName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbIdentityKey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbIdentityKey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbIdentityKey entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
