package com.apap.director.db.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DB_IDENTITY_KEY".
 */
@Entity
public class DbIdentityKey {

    @Id(autoincrement = true)
    private Long id;
    private Integer deviceId;
    private String name;
    private byte[] key;
    private String identityName;

    @Generated
    public DbIdentityKey() {
    }

    public DbIdentityKey(Long id) {
        this.id = id;
    }

    @Generated
    public DbIdentityKey(Long id, Integer deviceId, String name, byte[] key, String identityName) {
        this.id = id;
        this.deviceId = deviceId;
        this.name = name;
        this.key = key;
        this.identityName = identityName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getKey() {
        return key;
    }

    public void setKey(byte[] key) {
        this.key = key;
    }

    public String getIdentityName() {
        return identityName;
    }

    public void setIdentityName(String identityName) {
        this.identityName = identityName;
    }

}
