package com.apap.director.db.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DB_PRE_KEY".
 */
@Entity
public class DbPreKey {

    @Id(autoincrement = true)
    private Long id;
    private Integer dbPreKeyId;
    private byte[] privateKey;
    private byte[] publicKey;

    @Generated
    public DbPreKey() {
    }

    public DbPreKey(Long id) {
        this.id = id;
    }

    @Generated
    public DbPreKey(Long id, Integer dbPreKeyId, byte[] privateKey, byte[] publicKey) {
        this.id = id;
        this.dbPreKeyId = dbPreKeyId;
        this.privateKey = privateKey;
        this.publicKey = publicKey;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDbPreKeyId() {
        return dbPreKeyId;
    }

    public void setDbPreKeyId(Integer dbPreKeyId) {
        this.dbPreKeyId = dbPreKeyId;
    }

    public byte[] getPrivateKey() {
        return privateKey;
    }

    public void setPrivateKey(byte[] privateKey) {
        this.privateKey = privateKey;
    }

    public byte[] getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(byte[] publicKey) {
        this.publicKey = publicKey;
    }

}
