package com.apap.director.db.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DB_PRE_KEY".
 */
@Entity
public class DbPreKey {

    @Id(autoincrement = true)
    private Long id;
    private Integer dbPreKeyId;
    private byte[] serialized;

    @Generated
    public DbPreKey() {
    }

    public DbPreKey(Long id) {
        this.id = id;
    }

    @Generated
    public DbPreKey(Long id, Integer dbPreKeyId, byte[] serialized) {
        this.id = id;
        this.dbPreKeyId = dbPreKeyId;
        this.serialized = serialized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDbPreKeyId() {
        return dbPreKeyId;
    }

    public void setDbPreKeyId(Integer dbPreKeyId) {
        this.dbPreKeyId = dbPreKeyId;
    }

    public byte[] getSerialized() {
        return serialized;
    }

    public void setSerialized(byte[] serialized) {
        this.serialized = serialized;
    }

}
