package com.apap.director.db.dao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_PRE_KEY".
*/
public class DbPreKeyDao extends AbstractDao<DbPreKey, Long> {

    public static final String TABLENAME = "DB_PRE_KEY";

    /**
     * Properties of entity DbPreKey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DbPreKeyId = new Property(1, Integer.class, "dbPreKeyId", false, "DB_PRE_KEY_ID");
        public final static Property PrivateKey = new Property(2, byte[].class, "privateKey", false, "PRIVATE_KEY");
        public final static Property PublicKey = new Property(3, byte[].class, "publicKey", false, "PUBLIC_KEY");
    }


    public DbPreKeyDao(DaoConfig config) {
        super(config);
    }
    
    public DbPreKeyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_PRE_KEY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DB_PRE_KEY_ID\" INTEGER," + // 1: dbPreKeyId
                "\"PRIVATE_KEY\" BLOB," + // 2: privateKey
                "\"PUBLIC_KEY\" BLOB);"); // 3: publicKey
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_PRE_KEY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbPreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer dbPreKeyId = entity.getDbPreKeyId();
        if (dbPreKeyId != null) {
            stmt.bindLong(2, dbPreKeyId);
        }
 
        byte[] privateKey = entity.getPrivateKey();
        if (privateKey != null) {
            stmt.bindBlob(3, privateKey);
        }
 
        byte[] publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindBlob(4, publicKey);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbPreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer dbPreKeyId = entity.getDbPreKeyId();
        if (dbPreKeyId != null) {
            stmt.bindLong(2, dbPreKeyId);
        }
 
        byte[] privateKey = entity.getPrivateKey();
        if (privateKey != null) {
            stmt.bindBlob(3, privateKey);
        }
 
        byte[] publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindBlob(4, publicKey);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbPreKey readEntity(Cursor cursor, int offset) {
        DbPreKey entity = new DbPreKey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // dbPreKeyId
            cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2), // privateKey
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3) // publicKey
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbPreKey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDbPreKeyId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPrivateKey(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
        entity.setPublicKey(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbPreKey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbPreKey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbPreKey entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
