package com.apap.director.db.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DB_SESSION".
 */
@Entity
public class DbSession {

    @Id(autoincrement = true)
    private Long id;
    private Integer deviceId;
    private String name;
    private byte[] serialized;

    @Generated
    public DbSession() {
    }

    public DbSession(Long id) {
        this.id = id;
    }

    @Generated
    public DbSession(Long id, Integer deviceId, String name, byte[] serialized) {
        this.id = id;
        this.deviceId = deviceId;
        this.name = name;
        this.serialized = serialized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getSerialized() {
        return serialized;
    }

    public void setSerialized(byte[] serialized) {
        this.serialized = serialized;
    }

}
