package com.apap.director.db.dao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_SIGNED_PRE_KEY".
*/
public class DbSignedPreKeyDao extends AbstractDao<DbSignedPreKey, Long> {

    public static final String TABLENAME = "DB_SIGNED_PRE_KEY";

    /**
     * Properties of entity DbSignedPreKey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DbSignedPreKeyId = new Property(1, Integer.class, "dbSignedPreKeyId", false, "DB_SIGNED_PRE_KEY_ID");
        public final static Property PrivateKey = new Property(2, byte[].class, "privateKey", false, "PRIVATE_KEY");
        public final static Property PublicKey = new Property(3, byte[].class, "publicKey", false, "PUBLIC_KEY");
        public final static Property Signature = new Property(4, byte[].class, "signature", false, "SIGNATURE");
    }


    public DbSignedPreKeyDao(DaoConfig config) {
        super(config);
    }
    
    public DbSignedPreKeyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_SIGNED_PRE_KEY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DB_SIGNED_PRE_KEY_ID\" INTEGER," + // 1: dbSignedPreKeyId
                "\"PRIVATE_KEY\" BLOB," + // 2: privateKey
                "\"PUBLIC_KEY\" BLOB," + // 3: publicKey
                "\"SIGNATURE\" BLOB);"); // 4: signature
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_SIGNED_PRE_KEY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbSignedPreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer dbSignedPreKeyId = entity.getDbSignedPreKeyId();
        if (dbSignedPreKeyId != null) {
            stmt.bindLong(2, dbSignedPreKeyId);
        }
 
        byte[] privateKey = entity.getPrivateKey();
        if (privateKey != null) {
            stmt.bindBlob(3, privateKey);
        }
 
        byte[] publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindBlob(4, publicKey);
        }
 
        byte[] signature = entity.getSignature();
        if (signature != null) {
            stmt.bindBlob(5, signature);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbSignedPreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer dbSignedPreKeyId = entity.getDbSignedPreKeyId();
        if (dbSignedPreKeyId != null) {
            stmt.bindLong(2, dbSignedPreKeyId);
        }
 
        byte[] privateKey = entity.getPrivateKey();
        if (privateKey != null) {
            stmt.bindBlob(3, privateKey);
        }
 
        byte[] publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindBlob(4, publicKey);
        }
 
        byte[] signature = entity.getSignature();
        if (signature != null) {
            stmt.bindBlob(5, signature);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbSignedPreKey readEntity(Cursor cursor, int offset) {
        DbSignedPreKey entity = new DbSignedPreKey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // dbSignedPreKeyId
            cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2), // privateKey
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3), // publicKey
            cursor.isNull(offset + 4) ? null : cursor.getBlob(offset + 4) // signature
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbSignedPreKey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDbSignedPreKeyId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPrivateKey(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
        entity.setPublicKey(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
        entity.setSignature(cursor.isNull(offset + 4) ? null : cursor.getBlob(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbSignedPreKey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbSignedPreKey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbSignedPreKey entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
