package com.apap.director.db.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DB_SIGNED_PRE_KEY".
 */
@Entity
public class DbSignedPreKey {

    @Id(autoincrement = true)
    private Long id;
    private Integer dbSignedPreKeyId;
    private byte[] serialized;

    @Generated
    public DbSignedPreKey() {
    }

    public DbSignedPreKey(Long id) {
        this.id = id;
    }

    @Generated
    public DbSignedPreKey(Long id, Integer dbSignedPreKeyId, byte[] serialized) {
        this.id = id;
        this.dbSignedPreKeyId = dbSignedPreKeyId;
        this.serialized = serialized;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDbSignedPreKeyId() {
        return dbSignedPreKeyId;
    }

    public void setDbSignedPreKeyId(Integer dbSignedPreKeyId) {
        this.dbSignedPreKeyId = dbSignedPreKeyId;
    }

    public byte[] getSerialized() {
        return serialized;
    }

    public void setSerialized(byte[] serialized) {
        this.serialized = serialized;
    }

}
