package com.apap.director.db.dao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_SIGNED_PRE_KEY".
*/
public class DbSignedPreKeyDao extends AbstractDao<DbSignedPreKey, Long> {

    public static final String TABLENAME = "DB_SIGNED_PRE_KEY";

    /**
     * Properties of entity DbSignedPreKey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DbSignedPreKeyId = new Property(1, Integer.class, "dbSignedPreKeyId", false, "DB_SIGNED_PRE_KEY_ID");
        public final static Property Serialized = new Property(2, byte[].class, "serialized", false, "SERIALIZED");
        public final static Property IdentityName = new Property(3, String.class, "identityName", false, "IDENTITY_NAME");
    }


    public DbSignedPreKeyDao(DaoConfig config) {
        super(config);
    }
    
    public DbSignedPreKeyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_SIGNED_PRE_KEY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DB_SIGNED_PRE_KEY_ID\" INTEGER," + // 1: dbSignedPreKeyId
                "\"SERIALIZED\" BLOB," + // 2: serialized
                "\"IDENTITY_NAME\" TEXT);"); // 3: identityName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_SIGNED_PRE_KEY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbSignedPreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer dbSignedPreKeyId = entity.getDbSignedPreKeyId();
        if (dbSignedPreKeyId != null) {
            stmt.bindLong(2, dbSignedPreKeyId);
        }
 
        byte[] serialized = entity.getSerialized();
        if (serialized != null) {
            stmt.bindBlob(3, serialized);
        }
 
        String identityName = entity.getIdentityName();
        if (identityName != null) {
            stmt.bindString(4, identityName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbSignedPreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer dbSignedPreKeyId = entity.getDbSignedPreKeyId();
        if (dbSignedPreKeyId != null) {
            stmt.bindLong(2, dbSignedPreKeyId);
        }
 
        byte[] serialized = entity.getSerialized();
        if (serialized != null) {
            stmt.bindBlob(3, serialized);
        }
 
        String identityName = entity.getIdentityName();
        if (identityName != null) {
            stmt.bindString(4, identityName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbSignedPreKey readEntity(Cursor cursor, int offset) {
        DbSignedPreKey entity = new DbSignedPreKey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // dbSignedPreKeyId
            cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2), // serialized
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // identityName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbSignedPreKey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDbSignedPreKeyId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSerialized(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
        entity.setIdentityName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbSignedPreKey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbSignedPreKey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbSignedPreKey entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
