package com.apap.director.db.dao.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DB_SIGNED_PRE_KEY".
 */
@Entity
public class DbSignedPreKey {

    @Id(autoincrement = true)
    private Long id;
    private Integer dbSignedPreKeyId;
    private byte[] privateKey;
    private byte[] publicKey;
    private byte[] signature;

    @Generated
    public DbSignedPreKey() {
    }

    public DbSignedPreKey(Long id) {
        this.id = id;
    }

    @Generated
    public DbSignedPreKey(Long id, Integer dbSignedPreKeyId, byte[] privateKey, byte[] publicKey, byte[] signature) {
        this.id = id;
        this.dbSignedPreKeyId = dbSignedPreKeyId;
        this.privateKey = privateKey;
        this.publicKey = publicKey;
        this.signature = signature;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDbSignedPreKeyId() {
        return dbSignedPreKeyId;
    }

    public void setDbSignedPreKeyId(Integer dbSignedPreKeyId) {
        this.dbSignedPreKeyId = dbSignedPreKeyId;
    }

    public byte[] getPrivateKey() {
        return privateKey;
    }

    public void setPrivateKey(byte[] privateKey) {
        this.privateKey = privateKey;
    }

    public byte[] getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(byte[] publicKey) {
        this.publicKey = publicKey;
    }

    public byte[] getSignature() {
        return signature;
    }

    public void setSignature(byte[] signature) {
        this.signature = signature;
    }

}
