package com.apap.director.db.dao.model;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE".
*/
public class MessageDao extends AbstractDao<Message, Long> {

    public static final String TABLENAME = "MESSAGE";

    /**
     * Properties of entity Message.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sender = new Property(1, String.class, "sender", false, "SENDER");
        public final static Property Recipient = new Property(2, String.class, "recipient", false, "RECIPIENT");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property Date = new Property(4, java.util.Date.class, "date", false, "DATE");
        public final static Property Mine = new Property(5, Boolean.class, "mine", false, "MINE");
        public final static Property ConversationId = new Property(6, long.class, "conversationId", false, "CONVERSATION_ID");
    }

    private Query<Message> conversation_MessagesQuery;

    public MessageDao(DaoConfig config) {
        super(config);
    }
    
    public MessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SENDER\" TEXT," + // 1: sender
                "\"RECIPIENT\" TEXT NOT NULL ," + // 2: recipient
                "\"CONTENT\" TEXT NOT NULL ," + // 3: content
                "\"DATE\" INTEGER NOT NULL ," + // 4: date
                "\"MINE\" INTEGER," + // 5: mine
                "\"CONVERSATION_ID\" INTEGER NOT NULL );"); // 6: conversationId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Message entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sender = entity.getSender();
        if (sender != null) {
            stmt.bindString(2, sender);
        }
        stmt.bindString(3, entity.getRecipient());
        stmt.bindString(4, entity.getContent());
        stmt.bindLong(5, entity.getDate().getTime());
 
        Boolean mine = entity.getMine();
        if (mine != null) {
            stmt.bindLong(6, mine ? 1L: 0L);
        }
        stmt.bindLong(7, entity.getConversationId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Message entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String sender = entity.getSender();
        if (sender != null) {
            stmt.bindString(2, sender);
        }
        stmt.bindString(3, entity.getRecipient());
        stmt.bindString(4, entity.getContent());
        stmt.bindLong(5, entity.getDate().getTime());
 
        Boolean mine = entity.getMine();
        if (mine != null) {
            stmt.bindLong(6, mine ? 1L: 0L);
        }
        stmt.bindLong(7, entity.getConversationId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Message readEntity(Cursor cursor, int offset) {
        Message entity = new Message( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sender
            cursor.getString(offset + 2), // recipient
            cursor.getString(offset + 3), // content
            new java.util.Date(cursor.getLong(offset + 4)), // date
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // mine
            cursor.getLong(offset + 6) // conversationId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Message entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSender(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRecipient(cursor.getString(offset + 2));
        entity.setContent(cursor.getString(offset + 3));
        entity.setDate(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setMine(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setConversationId(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Message entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Message entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Message entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "messages" to-many relationship of Conversation. */
    public List<Message> _queryConversation_Messages(long conversationId) {
        synchronized (this) {
            if (conversation_MessagesQuery == null) {
                QueryBuilder<Message> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ConversationId.eq(null));
                conversation_MessagesQuery = queryBuilder.build();
            }
        }
        Query<Message> query = conversation_MessagesQuery.forCurrentThread();
        query.setParameter(0, conversationId);
        return query.list();
    }

}
