package com.apap.director.db.dao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SIGNED_PRE_KEY".
*/
public class SignedPreKeyDao extends AbstractDao<SignedPreKey, Long> {

    public static final String TABLENAME = "SIGNED_PRE_KEY";

    /**
     * Properties of entity SignedPreKey.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SignedPreKeyId = new Property(1, Integer.class, "signedPreKeyId", false, "SIGNED_PRE_KEY_ID");
        public final static Property Serialized = new Property(2, byte[].class, "serialized", false, "SERIALIZED");
    }


    public SignedPreKeyDao(DaoConfig config) {
        super(config);
    }
    
    public SignedPreKeyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SIGNED_PRE_KEY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SIGNED_PRE_KEY_ID\" INTEGER," + // 1: signedPreKeyId
                "\"SERIALIZED\" BLOB);"); // 2: serialized
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SIGNED_PRE_KEY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SignedPreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer signedPreKeyId = entity.getSignedPreKeyId();
        if (signedPreKeyId != null) {
            stmt.bindLong(2, signedPreKeyId);
        }
 
        byte[] serialized = entity.getSerialized();
        if (serialized != null) {
            stmt.bindBlob(3, serialized);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SignedPreKey entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer signedPreKeyId = entity.getSignedPreKeyId();
        if (signedPreKeyId != null) {
            stmt.bindLong(2, signedPreKeyId);
        }
 
        byte[] serialized = entity.getSerialized();
        if (serialized != null) {
            stmt.bindBlob(3, serialized);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SignedPreKey readEntity(Cursor cursor, int offset) {
        SignedPreKey entity = new SignedPreKey( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // signedPreKeyId
            cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2) // serialized
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SignedPreKey entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSignedPreKeyId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSerialized(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SignedPreKey entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SignedPreKey entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SignedPreKey entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
